In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import style

from sklearn.linear_model import LinearRegression, Lasso, LassoCV, Ridge, RidgeCV
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, PolynomialFeatures
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.feature_selection import RFECV

ModuleNotFoundError: No module named 'numpy'

In [2]:
plt.figure(figsize=(20, 10))

<Figure size 1440x720 with 0 Axes>

<Figure size 1440x720 with 0 Axes>

In [3]:
file = 'energydata_complete.csv'

In [4]:
energy_data = pd.read_csv(file)

In [5]:
energy_data

date  Appliances  lights         T1       RH_1  \
0      2016-01-11 17:00:00          60      30  19.890000  47.596667   
1      2016-01-11 17:10:00          60      30  19.890000  46.693333   
2      2016-01-11 17:20:00          50      30  19.890000  46.300000   
3      2016-01-11 17:30:00          50      40  19.890000  46.066667   
4      2016-01-11 17:40:00          60      40  19.890000  46.333333   
...                    ...         ...     ...        ...        ...   
19730  2016-05-27 17:20:00         100       0  25.566667  46.560000   
19731  2016-05-27 17:30:00          90       0  25.500000  46.500000   
19732  2016-05-27 17:40:00         270      10  25.500000  46.596667   
19733  2016-05-27 17:50:00         420      10  25.500000  46.990000   
19734  2016-05-27 18:00:00         430      10  25.500000  46.600000   

              T2       RH_2         T3       RH_3         T4  ...         T9  \
0      19.200000  44.790000  19.790000  44.730000  19.000000  ...  17.033333   
1      19.200000  44.722500  19.790000  44.790000  19.000000  ...  17.066667   
2      19.200000  44.626667  19.790000  44.933333  18.926667  ...  17.000000   
3      19.200000  44.590000  19.790000  45.000000  18.890000  ...  17.000000   
4      19.200000  44.530000  19.790000  45.000000  18.890000  ...  17.000000   
...          ...        ...        ...        ...        ...  ...        ...   
19730  25.890000  42.025714  27.200000  41.163333  24.700000  ...  23.200000   
19731  25.754000  42.080000  27.133333  41.223333  24.700000  ...  23.200000   
19732  25.628571  42.768571  27.050000  41.690000  24.700000  ...  23.200000   
19733  25.414000  43.036000  26.890000  41.290000  24.700000  ...  23.200000   
19734  25.264286  42.971429  26.823333  41.156667  24.700000  ...  23.200000   

          RH_9      T_out  Press_mm_hg     RH_out  Windspeed  Visibility  \
0      45.5300   6.600000        733.5  92.000000   7.000000   63.000000   
1      45.5600   6.483333        733.6  92.000000   6.666667   59.166667   
2      45.5000   6.366667        733.7  92.000000   6.333333   55.333333   
3      45.4000   6.250000        733.8  92.000000   6.000000   51.500000   
4      45.4000   6.133333        733.9  92.000000   5.666667   47.666667   
...        ...        ...          ...        ...        ...         ...   
19730  46.7900  22.733333        755.2  55.666667   3.333333   23.666667   
19731  46.7900  22.600000        755.2  56.000000   3.500000   24.500000   
19732  46.7900  22.466667        755.2  56.333333   3.666667   25.333333   
19733  46.8175  22.333333        755.2  56.666667   3.833333   26.166667   
19734  46.8450  22.200000        755.2  57.000000   4.000000   27.000000   

       Tdewpoint        rv1        rv2  
0       5.300000  13.275433  13.275433  
1       5.200000  18.606195  18.606195  
2       5.100000  28.642668  28.642668  
3       5.000000  45.410389  45.410389  
4       4.900000  10.084097  10.084097  
...          ...        ...        ...  
19730  13.333333  43.096812  43.096812  
19731  13.300000  49.282940  49.282940  
19732  13.266667  29.199117  29.199117  
19733  13.233333   6.322784   6.322784  
19734  13.200000  34.118851  34.118851  

[19735 rows x 29 columns]

In [6]:
energy_data.describe()

Appliances        lights            T1          RH_1            T2  \
count  19735.000000  19735.000000  19735.000000  19735.000000  19735.000000   
mean      97.694958      3.801875     21.686571     40.259739     20.341219   
std      102.524891      7.935988      1.606066      3.979299      2.192974   
min       10.000000      0.000000     16.790000     27.023333     16.100000   
25%       50.000000      0.000000     20.760000     37.333333     18.790000   
50%       60.000000      0.000000     21.600000     39.656667     20.000000   
75%      100.000000      0.000000     22.600000     43.066667     21.500000   
max     1080.000000     70.000000     26.260000     63.360000     29.856667   

               RH_2            T3          RH_3            T4          RH_4  \
count  19735.000000  19735.000000  19735.000000  19735.000000  19735.000000   
mean      40.420420     22.267611     39.242500     20.855335     39.026904   
std        4.069813      2.006111      3.254576      2.042884      4.341321   
min       20.463333     17.200000     28.766667     15.100000     27.660000   
25%       37.900000     20.790000     36.900000     19.530000     35.530000   
50%       40.500000     22.100000     38.530000     20.666667     38.400000   
75%       43.260000     23.290000     41.760000     22.100000     42.156667   
max       56.026667     29.236000     50.163333     26.200000     51.090000   

       ...            T9          RH_9         T_out   Press_mm_hg  \
count  ...  19735.000000  19735.000000  19735.000000  19735.000000   
mean   ...     19.485828     41.552401      7.411665    755.522602   
std    ...      2.014712      4.151497      5.317409      7.399441   
min    ...     14.890000     29.166667     -5.000000    729.300000   
25%    ...     18.000000     38.500000      3.666667    750.933333   
50%    ...     19.390000     40.900000      6.916667    756.100000   
75%    ...     20.600000     44.338095     10.408333    760.933333   
max    ...     24.500000     53.326667     26.100000    772.300000   

             RH_out     Windspeed    Visibility     Tdewpoint           rv1  \
count  19735.000000  19735.000000  19735.000000  19735.000000  19735.000000   
mean      79.750418      4.039752     38.330834      3.760707     24.988033   
std       14.901088      2.451221     11.794719      4.194648     14.496634   
min       24.000000      0.000000      1.000000     -6.600000      0.005322   
25%       70.333333      2.000000     29.000000      0.900000     12.497889   
50%       83.666667      3.666667     40.000000      3.433333     24.897653   
75%       91.666667      5.500000     40.000000      6.566667     37.583769   
max      100.000000     14.000000     66.000000     15.500000     49.996530   

                rv2  
count  19735.000000  
mean      24.988033  
std       14.496634  
min        0.005322  
25%       12.497889  
50%       24.897653  
75%       37.583769  
max       49.996530  

[8 rows x 28 columns]

In [7]:
energy_data.drop(['date', 'lights'], inplace=True, axis=1)

In [8]:
energy_data

Appliances         T1       RH_1         T2       RH_2         T3  \
0              60  19.890000  47.596667  19.200000  44.790000  19.790000   
1              60  19.890000  46.693333  19.200000  44.722500  19.790000   
2              50  19.890000  46.300000  19.200000  44.626667  19.790000   
3              50  19.890000  46.066667  19.200000  44.590000  19.790000   
4              60  19.890000  46.333333  19.200000  44.530000  19.790000   
...           ...        ...        ...        ...        ...        ...   
19730         100  25.566667  46.560000  25.890000  42.025714  27.200000   
19731          90  25.500000  46.500000  25.754000  42.080000  27.133333   
19732         270  25.500000  46.596667  25.628571  42.768571  27.050000   
19733         420  25.500000  46.990000  25.414000  43.036000  26.890000   
19734         430  25.500000  46.600000  25.264286  42.971429  26.823333   

            RH_3         T4       RH_4         T5  ...         T9     RH_9  \
0      44.730000  19.000000  45.566667  17.166667  ...  17.033333  45.5300   
1      44.790000  19.000000  45.992500  17.166667  ...  17.066667  45.5600   
2      44.933333  18.926667  45.890000  17.166667  ...  17.000000  45.5000   
3      45.000000  18.890000  45.723333  17.166667  ...  17.000000  45.4000   
4      45.000000  18.890000  45.530000  17.200000  ...  17.000000  45.4000   
...          ...        ...        ...        ...  ...        ...      ...   
19730  41.163333  24.700000  45.590000  23.200000  ...  23.200000  46.7900   
19731  41.223333  24.700000  45.590000  23.230000  ...  23.200000  46.7900   
19732  41.690000  24.700000  45.730000  23.230000  ...  23.200000  46.7900   
19733  41.290000  24.700000  45.790000  23.200000  ...  23.200000  46.8175   
19734  41.156667  24.700000  45.963333  23.200000  ...  23.200000  46.8450   

           T_out  Press_mm_hg     RH_out  Windspeed  Visibility  Tdewpoint  \
0       6.600000        733.5  92.000000   7.000000   63.000000   5.300000   
1       6.483333        733.6  92.000000   6.666667   59.166667   5.200000   
2       6.366667        733.7  92.000000   6.333333   55.333333   5.100000   
3       6.250000        733.8  92.000000   6.000000   51.500000   5.000000   
4       6.133333        733.9  92.000000   5.666667   47.666667   4.900000   
...          ...          ...        ...        ...         ...        ...   
19730  22.733333        755.2  55.666667   3.333333   23.666667  13.333333   
19731  22.600000        755.2  56.000000   3.500000   24.500000  13.300000   
19732  22.466667        755.2  56.333333   3.666667   25.333333  13.266667   
19733  22.333333        755.2  56.666667   3.833333   26.166667  13.233333   
19734  22.200000        755.2  57.000000   4.000000   27.000000  13.200000   

             rv1        rv2  
0      13.275433  13.275433  
1      18.606195  18.606195  
2      28.642668  28.642668  
3      45.410389  45.410389  
4      10.084097  10.084097  
...          ...        ...  
19730  43.096812  43.096812  
19731  49.282940  49.282940  
19732  29.199117  29.199117  
19733   6.322784   6.322784  
19734  34.118851  34.118851  

[19735 rows x 27 columns]

In [9]:
energy_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 27 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Appliances   19735 non-null  int64  
 1   T1           19735 non-null  float64
 2   RH_1         19735 non-null  float64
 3   T2           19735 non-null  float64
 4   RH_2         19735 non-null  float64
 5   T3           19735 non-null  float64
 6   RH_3         19735 non-null  float64
 7   T4           19735 non-null  float64
 8   RH_4         19735 non-null  float64
 9   T5           19735 non-null  float64
 10  RH_5         19735 non-null  float64
 11  T6           19735 non-null  float64
 12  RH_6         19735 non-null  float64
 13  T7           19735 non-null  float64
 14  RH_7         19735 non-null  float64
 15  T8           19735 non-null  float64
 16  RH_8         19735 non-null  float64
 17  T9           19735 non-null  float64
 18  RH_9         19735 non-null  float64
 19  T_ou

In [10]:
features = energy_data.iloc[:, 1:]
target = energy_data.iloc[:, 0]

In [21]:
cols = features.columns
cols

Index(['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5',
       'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9', 'T_out',
       'Press_mm_hg', 'RH_out', 'Windspeed', 'Visibility', 'Tdewpoint', 'rv1',
       'rv2'],
      dtype='object')

In [12]:
target

0         60
1         60
2         50
3         50
4         60
        ... 
19730    100
19731     90
19732    270
19733    420
19734    430
Name: Appliances, Length: 19735, dtype: int64

In [23]:
data = features.values
data

array([[19.89      , 47.59666667, 19.2       , ...,  5.3       ,
        13.27543316, 13.27543316],
       [19.89      , 46.69333333, 19.2       , ...,  5.2       ,
        18.60619498, 18.60619498],
       [19.89      , 46.3       , 19.2       , ...,  5.1       ,
        28.64266817, 28.64266817],
       ...,
       [25.5       , 46.59666667, 25.62857143, ..., 13.26666667,
        29.19911708, 29.19911708],
       [25.5       , 46.99      , 25.414     , ..., 13.23333333,
         6.32278365,  6.32278365],
       [25.5       , 46.6       , 25.26428571, ..., 13.2       ,
        34.11885059, 34.11885059]])

In [14]:
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.3, random_state=42)

In [15]:
X_train.shape

(13814, 26)

In [25]:
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train

array([[0.49736008, 0.28300439, 0.12284953, ..., 0.19318182, 0.72450918,
        0.72450918],
       [0.28616684, 0.57686404, 0.18899927, ..., 0.34393939, 0.86401848,
        0.86401848],
       [0.42238648, 0.27554825, 0.0574267 , ..., 0.15909091, 0.49942021,
        0.49942021],
       ...,
       [0.36958817, 0.28541667, 0.15265326, ..., 0.16666667, 0.38128609,
        0.38128609],
       [0.5279831 , 0.2808114 , 0.31504725, ..., 0.11515152, 0.02074813,
        0.02074813],
       [0.47870468, 0.35219298, 0.27550279, ..., 0.49772727, 0.34896874,
        0.34896874]])

In [17]:
X_test

array([[0.43294615, 0.27554825, 0.12066877, ..., 0.3       , 0.51234794,
        0.51234794],
       [0.53854277, 0.85778509, 0.37727163, ..., 0.35454545, 0.46937859,
        0.46937859],
       [0.48574446, 0.27883772, 0.11146111, ..., 0.19090909, 0.00259746,
        0.00259746],
       ...,
       [0.43681802, 0.40712719, 0.18899927, ..., 0.51742424, 0.79266914,
        0.79266914],
       [0.55015839, 0.46732456, 0.33438333, ..., 0.52272727, 0.60824256,
        0.60824256],
       [0.43294615, 0.50219298, 0.21322995, ..., 0.74393939, 0.19877963,
        0.19877963]])

In [18]:
T2_index = 2
T6_index = 10
T2_train = X_train[T2_index]
T2_test = X_test[T2_index]
T2_train = X_train[T2_index]
T2_train = X_train[T2_index]

In [27]:
transformed_df = pd.DataFrame(X_train, columns=cols)
transformed_df

T1      RH_1        T2      RH_2        T3      RH_3        T4  \
0      0.497360  0.283004  0.122850  0.585114  0.373878  0.303474  0.476577   
1      0.286167  0.576864  0.188999  0.693396  0.217957  0.735317  0.270270   
2      0.422386  0.275548  0.057427  0.627256  0.373878  0.338059  0.414414   
3      0.560718  0.534101  0.280834  0.728807  0.514290  0.515189  0.540541   
4      0.835269  0.504496  1.000000  0.327578  0.745383  0.459106  0.900901   
...         ...       ...       ...       ...       ...       ...       ...   
13809  0.524815  0.456469  0.239157  0.658277  0.481888  0.478268  0.576577   
13810  0.591341  0.548575  0.428883  0.628329  0.456962  0.582489  0.557658   
13811  0.369588  0.285417  0.152653  0.497317  0.240944  0.412370  0.279279   
13812  0.527983  0.280811  0.315047  0.424915  0.332336  0.380122  0.540541   
13813  0.478705  0.352193  0.275503  0.525900  0.456962  0.365633  0.414414   

           RH_4        T5      RH_5  ...        T9      RH_9     T_out  \
0      0.239968  0.408027  0.155065  ...  0.475893  0.376380  0.168810   
1      0.681016  0.178691  0.330033  ...  0.240375  0.703504  0.262594   
2      0.210702  0.378404  0.147129  ...  0.468262  0.409803  0.110397   
3      0.469242  0.509317  0.421545  ...  0.561915  0.340784  0.444802   
4      0.500126  0.748845  0.452926  ...  0.854318  0.633278  0.849946   
...         ...       ...       ...  ...       ...       ...       ...   
13809  0.501450  0.455805  0.246895  ...  0.568852  0.471578  0.468382   
13810  0.692487  0.417582  0.281511  ...  0.561915  0.625966  0.717042   
13811  0.302912  0.302914  0.157287  ...  0.312175  0.426325  0.126474   
13812  0.319383  0.259914  0.241529  ...  0.375650  0.509106  0.227224   
13813  0.485714  0.369804  0.187791  ...  0.468262  0.500828  0.374598   

       Press_mm_hg    RH_out  Windspeed  Visibility  Tdewpoint       rv1  \
0         0.863125  0.776316   0.142857    0.984615   0.193182  0.724509   
1         0.836758  0.807018   0.142857    0.600000   0.343939  0.864018   
2         0.853819  0.859649   0.095238    0.917949   0.159091  0.499420   
3         0.559907  0.750000   0.119048    0.384615   0.560606  0.323062   
4         0.530438  0.355263   0.142857    0.600000   0.790909  0.340952   
...            ...       ...        ...         ...        ...       ...   
13809     0.492439  0.706140   0.476190    0.600000   0.565152  0.910303   
13810     0.469950  0.552632   0.142857    0.600000   0.795455  0.698662   
13811     0.595580  0.828947   0.261905    0.948718   0.166667  0.381286   
13812     0.831330  0.530702   0.095238    0.600000   0.115152  0.020748   
13813     0.682823  0.809211   0.071429    0.600000   0.497727  0.348969   

            rv2  
0      0.724509  
1      0.864018  
2      0.499420  
3      0.323062  
4      0.340952  
...         ...  
13809  0.910303  
13810  0.698662  
13811  0.381286  
13812  0.020748  
13813  0.348969  

[13814 rows x 26 columns]

In [29]:
test_df = pd.DataFrame(X_test, columns=cols)
test_df

T1      RH_1        T2      RH_2        T3      RH_3        T4  \
0     0.432946  0.275548  0.120669  0.543362  0.256730  0.380122  0.419820   
1     0.538543  0.857785  0.377272  0.724710  0.368339  0.956224  0.489489   
2     0.485744  0.278838  0.111461  0.583358  0.371109  0.300670  0.467568   
3     0.485744  0.460855  0.566271  0.416837  0.401573  0.381679  0.656757   
4     0.335093  0.266557  0.026411  0.571554  0.232635  0.356753  0.374775   
...        ...       ...       ...       ...       ...       ...       ...   
5916  0.560718  0.358882  0.370487  0.425422  0.386895  0.576414  0.608709   
5917  0.518479  0.370614  0.225345  0.613501  0.481888  0.446799  0.464865   
5918  0.436818  0.407127  0.188999  0.655643  0.381356  0.403490  0.422523   
5919  0.550158  0.467325  0.334383  0.623451  0.481888  0.468453  0.576577   
5920  0.432946  0.502193  0.213230  0.713101  0.365570  0.482474  0.414414   

          RH_4        T5      RH_5  ...        T9      RH_9     T_out  \
0     0.254822  0.312470  0.319301  ...  0.457856  0.408251  0.217578   
1     0.553364  0.224346  0.423819  ...  0.145682  0.622241  0.247588   
2     0.235409  0.408027  0.153024  ...  0.468262  0.377621  0.167203   
3     0.300529  0.411212  0.198020  ...  0.561915  0.388797  0.445338   
4     0.288647  0.244625  0.284685  ...  0.427680  0.477373  0.145766   
...        ...       ...       ...  ...       ...       ...       ...   
5916  0.471007  0.264692  0.300809  ...  0.312175  0.507726  0.220257   
5917  0.478066  0.446249  0.260499  ...  0.561915  0.528422  0.439443   
5918  0.435270  0.378404  0.226690  ...  0.490114  0.356926  0.392283   
5919  0.539687  0.503583  0.233694  ...  0.620881  0.417770  0.494105   
5920  0.575423  0.378404  0.239790  ...  0.479709  0.507726  0.583065   

      Press_mm_hg    RH_out  Windspeed  Visibility  Tdewpoint       rv1  \
0        0.921287  0.846491   0.166667    0.953846   0.300000  0.512348   
1        0.588600  0.868421   0.214286    0.400000   0.354545  0.469379   
2        0.858472  0.776316   0.142857    0.984615   0.190909  0.002597   
3        0.895696  0.616228   0.369048    0.600000   0.468939  0.205668   
4        0.938736  0.912281   0.285714    0.735897   0.234091  0.214886   
...           ...       ...        ...         ...        ...       ...   
5916     0.842187  0.756579   0.107143    0.430769   0.252273  0.910100   
5917     0.422257  0.651316   0.583333    0.600000   0.488636  0.975527   
5918     0.665762  0.796053   0.083333    0.969231   0.517424  0.792669   
5919     0.545948  0.596491   0.642857    0.600000   0.522727  0.608243   
5920     0.530826  0.734649   0.500000    0.505128   0.743939  0.198780   

           rv2  
0     0.512348  
1     0.469379  
2     0.002597  
3     0.205668  
4     0.214886  
...        ...  
5916  0.910100  
5917  0.975527  
5918  0.792669  
5919  0.608243  
5920  0.198780  

[5921 rows x 26 columns]

In [45]:
x = transformed_df['T2'].values.reshape(-1, 1)
y = transformed_df['T6'].values
x_pred = test_df['T2'].values.reshape(-1, 1)
y_true = test_df['T6'].values
y_true

array([0.21062271, 0.24941725, 0.16792929, ..., 0.45541958, 0.56018981,
       0.53991841])

In [41]:
reg = LinearRegression(n_jobs=-1)
reg.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=-1, normalize=False)

In [44]:
y_pred = reg.predict(x_pred)
y_pred

array([0.23851367, 0.46739978, 0.23030057, ..., 0.29946351, 0.42914403,
       0.32107693])

In [46]:
score = r2_score(y_true, y_pred)
score

0.6427789637197382

In [49]:
mae = mean_absolute_error(y_true, y_pred)
mae

0.08225349979986316

In [51]:
rss = np.sum(np.square(y_true - y_pred))
rss

66.25049903740734

In [53]:
rmse = mean_squared_error(y_true, y_pred)
rmse

0.011189072629185498

In [56]:
x

array([[0.12284953],
       [0.18899927],
       [0.0574267 ],
       ...,
       [0.15265326],
       [0.31504725],
       [0.27550279]])

In [58]:
ridge = Ridge(alpha=0.4)
ridge.fit(x, y)
y_pred_ridge = ridge.predict(x_pred)
rmse_ridge = mean_squared_error(y_true, y_pred_ridge)
rmse_ridge

0.011189081129098668

In [59]:
rmse - rmse_ridge

-8.499913169146556e-09

In [60]:
reg.coef_

array([0.89198583])

In [65]:
ols = LinearRegression()
ols.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [69]:
ols.coef_.argmax()

1

In [70]:
lass = Lasso(alpha=0.001)
lass.fit(X_train, y_train)

Lasso(alpha=0.001, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [75]:
np.sum(lass.coef_ == 0)

0

In [76]:
lass_pred = lass.predict(X_test)

In [77]:
lass_score = mean_squared_error(y_test, lass_pred)
lass_score

8768.57559268009

In [62]:
features

T1       RH_1         T2       RH_2         T3       RH_3  \
0      19.890000  47.596667  19.200000  44.790000  19.790000  44.730000   
1      19.890000  46.693333  19.200000  44.722500  19.790000  44.790000   
2      19.890000  46.300000  19.200000  44.626667  19.790000  44.933333   
3      19.890000  46.066667  19.200000  44.590000  19.790000  45.000000   
4      19.890000  46.333333  19.200000  44.530000  19.790000  45.000000   
...          ...        ...        ...        ...        ...        ...   
19730  25.566667  46.560000  25.890000  42.025714  27.200000  41.163333   
19731  25.500000  46.500000  25.754000  42.080000  27.133333  41.223333   
19732  25.500000  46.596667  25.628571  42.768571  27.050000  41.690000   
19733  25.500000  46.990000  25.414000  43.036000  26.890000  41.290000   
19734  25.500000  46.600000  25.264286  42.971429  26.823333  41.156667   

              T4       RH_4         T5       RH_5  ...         T9     RH_9  \
0      19.000000  45.566667  17.166667  55.200000  ...  17.033333  45.5300   
1      19.000000  45.992500  17.166667  55.200000  ...  17.066667  45.5600   
2      18.926667  45.890000  17.166667  55.090000  ...  17.000000  45.5000   
3      18.890000  45.723333  17.166667  55.090000  ...  17.000000  45.4000   
4      18.890000  45.530000  17.200000  55.090000  ...  17.000000  45.4000   
...          ...        ...        ...        ...  ...        ...      ...   
19730  24.700000  45.590000  23.200000  52.400000  ...  23.200000  46.7900   
19731  24.700000  45.590000  23.230000  52.326667  ...  23.200000  46.7900   
19732  24.700000  45.730000  23.230000  52.266667  ...  23.200000  46.7900   
19733  24.700000  45.790000  23.200000  52.200000  ...  23.200000  46.8175   
19734  24.700000  45.963333  23.200000  52.200000  ...  23.200000  46.8450   

           T_out  Press_mm_hg     RH_out  Windspeed  Visibility  Tdewpoint  \
0       6.600000        733.5  92.000000   7.000000   63.000000   5.300000   
1       6.483333        733.6  92.000000   6.666667   59.166667   5.200000   
2       6.366667        733.7  92.000000   6.333333   55.333333   5.100000   
3       6.250000        733.8  92.000000   6.000000   51.500000   5.000000   
4       6.133333        733.9  92.000000   5.666667   47.666667   4.900000   
...          ...          ...        ...        ...         ...        ...   
19730  22.733333        755.2  55.666667   3.333333   23.666667  13.333333   
19731  22.600000        755.2  56.000000   3.500000   24.500000  13.300000   
19732  22.466667        755.2  56.333333   3.666667   25.333333  13.266667   
19733  22.333333        755.2  56.666667   3.833333   26.166667  13.233333   
19734  22.200000        755.2  57.000000   4.000000   27.000000  13.200000   

             rv1        rv2  
0      13.275433  13.275433  
1      18.606195  18.606195  
2      28.642668  28.642668  
3      45.410389  45.410389  
4      10.084097  10.084097  
...          ...        ...  
19730  43.096812  43.096812  
19731  49.282940  49.282940  
19732  29.199117  29.199117  
19733   6.322784   6.322784  
19734  34.118851  34.118851  

[19735 rows x 26 columns]